### ISSUE TITLE
Plus "+" icon state inverted

### ISSUE THREAD

**Issue by dominicht** [CodyHouse/cd-accordion-changelog#1]
Hi, I think since the last update of this component, the Plus icon was inverted. It shows a + icon when the accordion item is already open and a Minus icon when it's closed. I think it should be the other way around.

To fix this, I changed the scss for this:

```
.accordion__icon-plus .icon__group { // animated plus icon
  transform: rotate(-90deg);

  > *:first-child {
    transform: rotate(-90deg);
  }
}

.accordion__item--is-open > .accordion__header {
  > .accordion__icon-plus .icon__group { // animated plus icon
    transform: rotate(0deg);

    > *:first-child {
      transform: rotate(0deg);
    }
  }
}
```

**Comment by sebastiano-guerriero** [comment]
Thanks for the heads up! I've just fixed the issue. The updated version will be available as soon as we deploy all the changes in a few hours.
