### ISSUE TITLE
Button within panel to open next panel

### ISSUE THREAD

**Issue by rene-haefliger** [CodyHouse/cd-accordion-changelog#2]
I want to use a button within a panel to open the following panel. How could I achieve this? Thanks a lot for your Help.

**Comment by claudia-romano** [comment]
Hi there, the best solution would be triggering the click on the `.js-accordion__trigger` element. Each one of the trigger has a `aria-controls` attribute that you can use to target the right panel.
Something like:
```javascript
button.addEventListener('click', function(){
  // trigger click event on accordion button
  document.querySelector('.js-accordion__trigger[aria-controls="accordion-content-1"]').click();
});
```
